### ISSUE TITLE
Unable to access https://gitext.gfz-potsdam.de/EnMAP/sentinel2_manual_classification_clouds

### ISSUE THREAD

**Issue by NakitaOza** [vkristoll/cloud-masking-SOMs#1]
Hi!  It is mentioned to run "read_h5file.py" as a first step of implementation of code. Here on line no. 7, it is mentioned to download a H5 file from https://gitext.gfz-potsdam.de/EnMAP/sentinel2_manual_classification_clouds .
I am unable to access this link. Is there an alternative link you can provide? Or add the file in this repository?

**Comment by vkristoll** [comment]
Hello! It seems that the link has changed. I found the one below and it seems to work.
https://git.gfz-potsdam.de/EnMAP/sentinel2_manual_classification_clouds

**Comment by NakitaOza** [comment]
Great! thanks!
