### ISSUE TITLE
data_preprocessing.py is trying to read file that does not exists

### ISSUE THREAD

**Issue by NakitaOza** [vkristoll/cloud-masking-SOMs#2]
Hi again!
After running `read_h5file.py`, I ran step 2 of running `data_preprocessing.py`. 
This file tried to read `2016_spectraSOMs.csv` and `2017_spectraSOMs.csv` which do not exist. The file mentions '

> The datasets are two .csv files which were created by extracting the spectra from two .h5 files as explained in the file "read_h5file.py".

No new file was created when I ran `read_h5file.py`. How can I get these files?
Please let me know.

**Comment by vkristoll** [comment]
Hello,
I added code in the file "read_h5file.py" in lines 34-42 to create and  save the file "2017_spectraSOMs.csv". To create the file "2016_spectraSOMs.csv", you need to update line 9 with the corresponding .h5 file for the year 2016. You also need
to change the name in line 42 accordingly.

**Comment by NakitaOza** [comment]
Perfect! It works now. Thanks! :)
